version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql_container_examFullStackM1DUJARDIN
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toto
      MYSQL_DATABASE: examM1Rh
    ports:
      - "3311:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: